(() => {
  const $ = (s, p=document) => p.querySelector(s);
  const $$ = (s, p=document) => [...p.querySelectorAll(s)];
  const tools = [
    {id:'small-font',icon:'𝒜',name:'Small Font Generator',category:'Text & Fonts',desc:'Convert plain text into a compact Unicode small-cap style.'},
    {id:'emoji',icon:'☺',name:'Emoji & Symbol Copy',category:'Text & Fonts',desc:'Search and copy real Unicode emoji and symbols.'},
    {id:'hex',icon:'◉',name:'HEX Color Generator',category:'Colors',desc:'Convert HEX into RGB, HSL, MiniMessage and Minecraft RGB.'},
    {id:'gradient',icon:'〰',name:'Gradient Generator',category:'Colors',desc:'Build live MiniMessage and per-character color gradients.'},
    {id:'minimessage',icon:'<>',name:'MiniMessage Builder',category:'Messages',desc:'Preview and generate common MiniMessage formats.'},
    {id:'title',icon:'▣',name:'Title Generator',category:'Messages',desc:'Generate ready-to-paste /title, actionbar and bossbar commands.'},
    {id:'motd',icon:'☄',name:'MOTD Generator',category:'Server Tools',desc:'Create two-line MOTDs with modern color syntax.'},
    {id:'gui',icon:'▦',name:'GUI Builder',category:'GUI Tools',desc:'Design a clickable inventory grid and export starter YAML.'},
    {id:'model',icon:'◇',name:'Sprite Model Generator',category:'Resource Packs',desc:'Generate an item model JSON file for custom model data.'},
    {id:'fontjson',icon:'Aa',name:'Font JSON Generator',category:'Resource Packs',desc:'Create valid bitmap font provider JSON.'},
    {id:'plugin',icon:'⌘',name:'plugin.yml Generator',category:'Plugins',desc:'Generate a clean Paper/Spigot plugin descriptor.'},
    {id:'json',icon:'{ }',name:'JSON Formatter & Validator',category:'Config Tools',desc:'Format, minify and validate JSON entirely locally.'},
    {id:'yaml',icon:'≡',name:'YAML Helper',category:'Config Tools',desc:'Indent and inspect YAML-style configuration text.'},
    {id:'command',icon:'/',name:'Command Generator',category:'Commands',desc:'Build a safe starter command for give, tellraw or playsound.'}
  ];
  const emojiData = [
    ['😀','grinning face','Smileys'],['✨','sparkles','Stars'],['⚔','crossed swords','Gaming'],['⚡','high voltage','Symbols'],['❤','red heart','Symbols'],['☄','comet','Nature'],['✦','four pointed star','Stars'],['☀','sun','Nature'],['☕','hot beverage','Food'],['🎮','video game','Gaming'],['⌘','command key','Technology'],['⚙','gear','Technology'],['➜','right arrow','Arrows'],['▲','up triangle','Shapes'],['◆','diamond','Shapes'],['₿','bitcoin sign','Currency'],['∞','infinity','Math'],['✓','check mark','Symbols'],['☠','skull and crossbones','Gaming'],['⚒','hammer and pick','Objects']
  ];
  const favs=()=>JSON.parse(localStorage.getItem('astra-favorites')||'[]');
  const saveFavs=v=>localStorage.setItem('astra-favorites',JSON.stringify(v));
  const recent=()=>JSON.parse(localStorage.getItem('astra-recent')||'[]');
  const saveRecent=v=>localStorage.setItem('astra-recent',JSON.stringify(v.slice(0,8)));
  function toast(msg='✓ Copied!'){const t=$('#toast');t.textContent=msg;t.className='toast show';setTimeout(()=>t.className='toast',1800)}
  async function copy(text){try{await navigator.clipboard.writeText(text);toast()}catch{const a=document.createElement('textarea');a.value=text;document.body.append(a);a.select();document.execCommand('copy');a.remove();toast()}}
  function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('✓ Download ready!')}
  function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
  function renderTools(list=tools){const f=favs();$('#toolGrid').innerHTML=list.map(t=>`<article class="tool-card" data-tool="${t.id}"><button class="favorite ${f.includes(t.id)?'on':''}" data-fav="${t.id}" aria-label="Favorite ${t.name}">${f.includes(t.id)?'★':'☆'}</button><div class="tool-icon">${t.icon}</div><h3>${t.name}</h3><p>${t.desc}</p><span class="tool-tag">${t.category.toUpperCase()}</span></article>`).join('')||'<p>No matching saved tools yet.</p>'}
  renderTools();
  function open(id){const t=tools.find(x=>x.id===id);if(!t)return;saveRecent([id,...recent().filter(x=>x!==id)]);$('#toolContent').innerHTML=toolHTML(id,t);$('#toolModal').classList.add('open');$('#toolModal').setAttribute('aria-hidden','false');bindTool(id)}
  function closeAll(){$$('.modal.open').forEach(m=>{m.classList.remove('open');m.setAttribute('aria-hidden','true')})}
  function output(label, id, text='', ext='txt'){return `<div class="panel"><h3>${label}</h3><pre class="output" id="${id}">${esc(text)}</pre><div class="output-actions"><button class="mini-btn" data-copy="#${id}">Copy</button><button class="mini-btn" data-download="#${id}" data-ext="${ext}">Download</button></div></div>`}
  function toolHTML(id,t){const header=`<div class="tool-header"><div class="eyebrow"><span></span>${t.category.toUpperCase()}</div><h2 id="toolTitle">${t.name}</h2><p>${t.desc} Works locally and preserves your formatting.</p></div>`;
    if(id==='small-font')return header+`<div class="tool-layout"><div class="panel"><h3>Input</h3><label class="field">TEXT<textarea id="textInput" placeholder="AstraUtilities">AstraUtilities</textarea></label><button class="btn primary" id="generate">Generate small font</button></div>${output('Generated text','result')}</div>`;
    if(id==='emoji')return header+`<div class="tool-layout"><div class="panel"><h3>Emoji & symbol library</h3><label class="field">SEARCH<input id="emojiSearch" placeholder="Search stars, gaming, arrows..." /></label><div id="emojiList" class="emoji-list"></div></div><div class="panel"><h3>Selected collection</h3><pre class="output" id="selectedEmoji"></pre><div class="output-actions"><button class="mini-btn" data-copy="#selectedEmoji">Copy selected</button><button class="mini-btn" id="clearEmoji">Clear</button></div><p class="notice">One click copies the actual Unicode character. Click “Add” to build a collection.</p></div></div>`;
    if(id==='hex')return header+`<div class="tool-layout"><div class="panel"><h3>Color input</h3><div class="form-row"><label class="field">HEX<input id="hexInput" value="#8B5CF6" /></label><label class="field">PICKER<input id="colorPicker" type="color" value="#8b5cf6" /></label></div><div class="color-swatch" id="swatch"></div><p class="notice" id="colorError"></p></div><div id="colorOutputs"></div></div>`;
    if(id==='gradient')return header+`<div class="tool-layout"><div class="panel"><h3>Gradient editor</h3><label class="field">TEXT<input id="gradText" value="AstraUtilities" /></label><div class="form-row"><label class="field">START<input id="gradStart" type="color" value="#8B5CF6" /></label><label class="field">END<input id="gradEnd" type="color" value="#06B6D4" /></label></div><button class="mini-btn" id="reverseGradient">Reverse</button> <button class="mini-btn" id="randomGradient">Randomize</button></div><div><div class="panel"><h3>Live preview</h3><div class="output gradient-text" id="gradPreview"></div></div>${output('MiniMessage','gradMini')}${output('Character-by-character Minecraft RGB','gradChars')}</div></div>`;
    if(id==='minimessage')return header+`<div class="tool-layout"><div class="panel"><h3>Message</h3><label class="field">MINIMESSAGE<textarea id="miniInput"><gradient:#8B5CF6:#06B6D4><bold>AstraUtilities</bold></gradient></textarea></label><div class="tool-tabs"><button class="tab" data-insert="<bold></bold>">Bold</button><button class="tab" data-insert="<italic></italic>">Italic</button><button class="tab" data-insert="<rainbow></rainbow>">Rainbow</button><button class="tab" data-insert="<color:#8B5CF6></color>">Color</button></div><p class="notice" id="miniStatus"></p></div><div>${output('Preview','miniPreview')}${output('Copyable MiniMessage','miniResult')}</div></div>`;
    if(id==='title')return header+`<div class="tool-layout"><div class="panel"><h3>Message command</h3><label class="field">TYPE<select id="msgType"><option value="title">Title</option><option value="actionbar">Actionbar</option><option value="bossbar">Bossbar</option><option value="tellraw">Tellraw</option></select></label><label class="field">TEXT<input id="msgText" value="Welcome to AstraUtilities" /></label><label class="field">COLOR<input id="msgColor" value="#8B5CF6" /></label><label class="field">TARGET<input id="msgTarget" value="@a" /></label></div>${output('Ready-to-paste command','commandOut')}</div>`;
    if(id==='motd')return header+`<div class="tool-layout"><div class="panel"><h3>Server MOTD</h3><label class="field">LINE ONE<input id="motd1" value="<gradient:#8B5CF6:#06B6D4>Astra Server</gradient>" /></label><label class="field">LINE TWO<input id="motd2" value="<gray>Free tools • No login required" /></label></div><div>${output('server.properties MOTD','motdOut')}${output('MiniMessage source','motdMini')}</div></div>`;
    if(id==='gui')return header+`<div class="tool-layout"><div class="panel"><h3>Inventory layout</h3><div class="form-row"><label class="field">ROWS<select id="guiRows"><option>3</option><option>1</option><option>2</option><option>4</option><option>5</option><option>6</option></select></label><label class="field">TITLE<input id="guiTitle" value="&8Astra Menu" /></label></div><div class="slot-grid" id="slotGrid"></div><p class="notice">Click a slot to toggle a DIAMOND item.</p></div>${output('Starter DeluxeMenus YAML','guiOut','menus.yml')}</div>`;
    if(id==='model')return header+`<div class="tool-layout"><div class="panel"><h3>Item model</h3><label class="field">MODEL NAME<input id="modelName" value="astra_blade" /></label><label class="field">TEXTURE PATH<input id="texturePath" value="astra:item/astra_blade" /></label><label class="field">CUSTOM MODEL DATA<input id="cmd" type="number" value="10001" /></label></div>${output('Model JSON','modelOut','astra_blade.json')}</div>`;
    if(id==='fontjson')return header+`<div class="tool-layout"><div class="panel"><h3>Bitmap provider</h3><label class="field">CHARACTER<input id="fontChar" value="✦" /></label><label class="field">TEXTURE PATH<input id="fontTexture" value="astra:font/icons.png" /></label><div class="form-row"><label class="field">HEIGHT<input id="fontHeight" type="number" value="8" /></label><label class="field">ASCENT<input id="fontAscent" type="number" value="7" /></label></div></div>${output('Font JSON','fontOut','default.json')}</div>`;
    if(id==='plugin')return header+`<div class="tool-layout"><div class="panel"><h3>Plugin details</h3><label class="field">NAME<input id="pluginName" value="AstraPlugin" /></label><label class="field">VERSION<input id="pluginVersion" value="1.0.0" /></label><label class="field">MAIN CLASS<input id="pluginMain" value="com.example.astra.AstraPlugin" /></label><label class="field">API VERSION<input id="pluginApi" value="1.21" /></label></div>${output('plugin.yml','pluginOut','plugin.yml')}</div>`;
    if(id==='json')return header+`<div class="tool-layout"><div class="panel"><h3>JSON input</h3><label class="field">PASTE JSON<textarea id="jsonInput">{"name":"AstraUtilities","free":true}</textarea></label><div class="output-actions"><button class="mini-btn" id="formatJson">Format</button><button class="mini-btn" id="minifyJson">Minify</button></div><p class="notice" id="jsonStatus"></p></div>${output('Result','jsonOut','output.json')}</div>`;
    if(id==='yaml')return header+`<div class="tool-layout"><div class="panel"><h3>YAML input</h3><label class="field">PASTE YAML<textarea id="yamlInput">items:
  astra_blade:
    display_name: "Astra Blade"
    amount: 1</textarea></label><button class="mini-btn" id="formatYaml">Normalize indentation</button><p class="notice" id="yamlStatus"></p></div>${output('Result','yamlOut','output.yml')}</div>`;
    return header+`<div class="tool-layout"><div class="panel"><h3>Command builder</h3><label class="field">COMMAND<select id="commandType"><option value="give">/give</option><option value="tellraw">/tellraw</option><option value="playsound">/playsound</option></select></label><label class="field">TARGET<input id="cmdTarget" value="@p" /></label><label class="field">VALUE<input id="cmdValue" value="minecraft:diamond 1" /></label></div>${output('Generated command','builderOut')}</div>`;
  }
  function setOut(id,text){const e=$(id);if(e)e.textContent=text}
  const smallMap={'a':'ᴀ','b':'ʙ','c':'ᴄ','d':'ᴅ','e':'ᴇ','f':'ꜰ','g':'ɢ','h':'ʜ','i':'ɪ','j':'ᴊ','k':'ᴋ','l':'ʟ','m':'ᴍ','n':'ɴ','o':'ᴏ','p':'ᴘ','q':'ǫ','r':'ʀ','s':'ꜱ','t':'ᴛ','u':'ᴜ','v':'ᴠ','w':'ᴡ','x':'x','y':'ʏ','z':'ᴢ'};
  const hexToRgb=h=>{h=h.replace('#','');if(!/^[\da-f]{6}$/i.test(h))return null;return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)]};
  function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;let max=Math.max(r,g,b),min=Math.min(r,g,b),h,s,l=(max+min)/2;if(max===min)h=s=0;else{let d=max-min;s=l>.5?d/(2-max-min):d/(max+min);switch(max){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;default:h=(r-g)/d+4}h/=6}return [Math.round(h*360),Math.round(s*100),Math.round(l*100)]}
  function parseHexColor(v){const rgb=hexToRgb(v);return rgb?`#${v.replace('#','').toUpperCase()}`:null}
  function interpolate(a,b,t){return a.map((x,i)=>Math.round(x+(b[i]-x)*t))}
  const rgbHex=a=>'#'+a.map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase();
  function bindTool(id){
    $$('[data-copy]').forEach(b=>b.onclick=()=>copy($(b.dataset.copy).textContent));$$('[data-download]').forEach(b=>b.onclick=()=>download('astra-output.'+b.dataset.ext,$(b.dataset.download).textContent));
    if(id==='small-font'){const f=()=>setOut('#result',($('#textInput').value||'').split('').map(c=>smallMap[c.toLowerCase()]||c).join(''));$('#textInput').oninput=f;$('#generate').onclick=f;f()}
    if(id==='emoji'){let selected=[];const render=()=>{const q=$('#emojiSearch').value.toLowerCase();$('#emojiList').innerHTML=emojiData.map((x,i)=>({...x,i})).filter(o=>o[1].includes(q)||o[2].toLowerCase().includes(q)||o[0].includes(q)).map(o=>`<div class="emoji-row"><b>${o[0]}</b><span>${o[1]}<small>${o[2]} · U+${o[0].codePointAt(0).toString(16).toUpperCase()}</small></span><button class="mini-btn" data-add="${o.i}">Add</button><button class="mini-btn" data-one="${o.i}">Copy</button></div>`).join('')||'<p class="notice">No symbols found.</p>';$$('[data-add]').forEach(b=>b.onclick=()=>{selected.push(emojiData[b.dataset.add][0]);setOut('#selectedEmoji',selected.join(''));toast('Added to collection')});$$('[data-one]').forEach(b=>b.onclick=()=>copy(emojiData[b.dataset.one][0]))};$('#emojiSearch').oninput=render;$('#clearEmoji').onclick=()=>{selected=[];setOut('#selectedEmoji','')};render()}
    if(id==='hex'){const f=()=>{const v=parseHexColor($('#hexInput').value);if(!v){$('#colorError').textContent='Invalid HEX color. Expected #RRGGBB, e.g. #8B5CF6.';$('#colorOutputs').innerHTML='';return}$('#colorError').textContent='';$('#hexInput').value=v;$('#colorPicker').value=v;$('#swatch').style.background=v;const [r,g,b]=hexToRgb(v),[h,s,l]=rgbToHsl(r,g,b), raw=v.slice(1),legacy='§x§'+raw.split('').join('§');$('#colorOutputs').innerHTML=output('Color formats','hexOut',`HEX\n${v}\n\nRGB\nrgb(${r}, ${g}, ${b})\n\nHSL\nhsl(${h}, ${s}%, ${l}%)\n\nMinecraft HEX\n&#${raw}\n\nMiniMessage\n<color:${v}>\n\nLegacy RGB\n${legacy}\n\nAmpersand RGB\n${legacy.replaceAll('§','&')}\n\nMinecraft JSON\n{"text":"Astra","color":"${v}"}`)};$('#hexInput').oninput=f;$('#colorPicker').oninput=()=>{$('#hexInput').value=$('#colorPicker').value;f()};f()}
    if(id==='gradient'){const f=()=>{const text=$('#gradText').value||'AstraUtilities',a=hexToRgb($('#gradStart').value),b=hexToRgb($('#gradEnd').value);$('#gradPreview').innerHTML=[...text].map((c,i)=>`<span style="color:${rgbHex(interpolate(a,b,text.length<2?0:i/(text.length-1)))}">${esc(c)}</span>`).join('');setOut('#gradMini',`<gradient:${$('#gradStart').value.toUpperCase()}:${$('#gradEnd').value.toUpperCase()}>${text}</gradient>`);setOut('#gradChars',[...text].map((c,i)=>{const h=rgbHex(interpolate(a,b,text.length<2?0:i/(text.length-1))).slice(1);return `§x§${h.split('').join('§')}${c}`}).join(''))};['#gradText','#gradStart','#gradEnd'].forEach(s=>$(s).oninput=f);$('#reverseGradient').onclick=()=>{let a=$('#gradStart').value;$('#gradStart').value=$('#gradEnd').value;$('#gradEnd').value=a;f()};$('#randomGradient').onclick=()=>{const c=()=>`#${Math.floor(Math.random()*16777215).toString(16).padStart(6,'0')}`;$('#gradStart').value=c();$('#gradEnd').value=c();f()};f()}
    if(id==='minimessage'){const f=()=>{const x=$('#miniInput').value;setOut('#miniResult',x);const valid=(x.match(/</g)||[]).length===(x.match(/>/g)||[]).length;$('#miniStatus').textContent=valid?'✓ Basic tag syntax looks balanced.':'Unbalanced angle brackets detected.';setOut('#miniPreview',x.replace(/<gradient:([^:>]+):([^>]+)>[\s\S]*?<\/gradient>/g,(_,a,b)=>`Gradient: ${a} → ${b}`).replace(/<[^>]+>/g,''))};$('#miniInput').oninput=f;$$('[data-insert]').forEach(b=>b.onclick=()=>{$('#miniInput').value+=b.dataset.insert;f()});f()}
    if(id==='title'){const f=()=>{const type=$('#msgType').value,target=$('#msgTarget').value||'@a',text=$('#msgText').value,color=$('#msgColor').value||'#FFFFFF';let o=type==='title'?`/title ${target} title {"text":"${text}","color":"${color}"}`:type==='actionbar'?`/title ${target} actionbar {"text":"${text}","color":"${color}"}`:type==='tellraw'?`/tellraw ${target} {"text":"${text}","color":"${color}"}`:`/bossbar add astra:message {"text":"${text}","color":"${color}"}`;setOut('#commandOut',o)};$$('#toolContent input, #toolContent select').forEach(e=>e.oninput=f);f()}
    if(id==='motd'){const f=()=>{const a=$('#motd1').value,b=$('#motd2').value;setOut('#motdOut',`motd=${a}\\n${b}`);setOut('#motdMini',a+'\n'+b)};$('#motd1').oninput=f;$('#motd2').oninput=f;f()}
    if(id==='gui'){let filled=new Set();const grid=()=>{$('#slotGrid').innerHTML=Array.from({length:+$('#guiRows').value*9},(_,i)=>`<button class="slot ${filled.has(i)?'filled':''}" data-slot="${i}">${filled.has(i)?'◆':i}</button>`).join('');$$('[data-slot]').forEach(b=>b.onclick=()=>{let i=+b.dataset.slot;filled.has(i)?filled.delete(i):filled.add(i);grid();out()})};const out=()=>{const title=$('#guiTitle').value||'&8Menu';let items=[...filled].map(i=>`  slot_${i}:\n    material: DIAMOND\n    slot: ${i}\n    display_name: "&bAstra Item"`).join('\n');setOut('#guiOut',`menu_title: "${title}"\nsize: ${+$('#guiRows').value*9}\nopen_command: menu\nitems:\n${items||'  # Click a slot to add an item.'}`)};$('#guiRows').onchange=()=>{filled=new Set([...filled].filter(i=>i<+$('#guiRows').value*9));grid();out()};$('#guiTitle').oninput=out;grid();out()}
    if(id==='model'){const f=()=>{const n=$('#modelName').value||'item',p=$('#texturePath').value||'namespace:item/item',d=+$('#cmd').value||1;setOut('#modelOut',JSON.stringify({parent:'minecraft:item/generated',textures:{layer0:p},overrides:[{predicate:{custom_model_data:d},model:`item/${n}`} ]},null,2))};$$('#toolContent input').forEach(x=>x.oninput=f);f()}
    if(id==='fontjson'){const f=()=>{const x={providers:[{type:'bitmap',file:$('#fontTexture').value,ascent:+$('#fontAscent').value,height:+$('#fontHeight').value,chars:[$('#fontChar').value||'✦']}]};setOut('#fontOut',JSON.stringify(x,null,2))};$$('#toolContent input').forEach(x=>x.oninput=f);f()}
    if(id==='plugin'){const f=()=>setOut('#pluginOut',`name: ${$('#pluginName').value}\nversion: ${$('#pluginVersion').value}\nmain: ${$('#pluginMain').value}\napi-version: '${$('#pluginApi').value}'\nauthor: AstraUtilities\ndescription: Generated with AstraUtilities`);$$('#toolContent input').forEach(x=>x.oninput=f);f()}
    if(id==='json'){const f=(mode='pretty')=>{try{const o=JSON.parse($('#jsonInput').value);setOut('#jsonOut',JSON.stringify(o,null,mode==='pretty'?2:0));$('#jsonStatus').textContent='✓ Valid JSON.'}catch(e){$('#jsonStatus').textContent='Invalid JSON: '+e.message;setOut('#jsonOut','')}};$('#formatJson').onclick=()=>f('pretty');$('#minifyJson').onclick=()=>f('mini');$('#jsonInput').oninput=()=>f('pretty');f()}
    if(id==='yaml'){const f=()=>{const text=$('#yamlInput').value.replace(/\t/g,'  ').split('\n').map(x=>x.replace(/\s+$/,'')).join('\n');setOut('#yamlOut',text);$('#yamlStatus').textContent=/^\s*[^#\s][^:]*:/m.test(text)?'✓ YAML-style keys detected. Indentation was normalized.':'Add at least one key followed by a colon.'};$('#formatYaml').onclick=f;$('#yamlInput').oninput=f;f()}
    if(id==='command'){const f=()=>{const type=$('#commandType').value,t=$('#cmdTarget').value||'@p',v=$('#cmdValue').value||'';let o=type==='give'?`/give ${t} ${v}`:type==='tellraw'?`/tellraw ${t} {"text":"${v}","color":"aqua"}`:`/playsound ${v} master ${t} ~ ~ ~ 1 1`;setOut('#builderOut',o)};$$('#toolContent input,#toolContent select').forEach(x=>x.oninput=f);f()}
  }
  document.addEventListener('click',e=>{const card=e.target.closest('[data-tool]');if(card&&!e.target.closest('[data-fav]'))open(card.dataset.tool);const fav=e.target.closest('[data-fav]');if(fav){e.stopPropagation();let f=favs(),id=fav.dataset.fav;f=f.includes(id)?f.filter(x=>x!==id):[...f,id];saveFavs(f);renderTools()};if(e.target.closest('[data-close]'))closeAll();const cat=e.target.closest('[data-open-tool]');if(cat)open(cat.dataset.openTool)});
  function showSearch(q=''){const modal=$('#searchModal');modal.classList.add('open');modal.setAttribute('aria-hidden','false');const input=$('#globalSearch');input.value=q;let selected=0;const render=()=>{const query=input.value.toLowerCase().trim();let arr=[...tools].sort((a,b)=>{const ar=recent().indexOf(a.id),br=recent().indexOf(b.id);return (ar<0?999:ar)-(br<0?999:br)}).filter(t=>!query||`${t.name} ${t.category} ${t.desc}`.toLowerCase().includes(query));$('#searchResults').innerHTML=arr.map((t,i)=>`<button class="search-result ${i===selected?'active':''}" data-result="${t.id}"><span class="result-icon">${t.icon}</span><span><b>${t.name}</b><small>${t.category} · ${t.desc}</small></span></button>`).join('')||'<p class="notice">No tools match that search.</p>';$$('[data-result]').forEach(b=>b.onclick=()=>{closeAll();open(b.dataset.result)})};input.oninput=()=>{selected=0;render()};input.onkeydown=e=>{let count=$$('[data-result]').length;if(e.key==='ArrowDown'){e.preventDefault();selected=Math.min(selected+1,Math.max(0,count-1));render()}if(e.key==='ArrowUp'){e.preventDefault();selected=Math.max(selected-1,0);render()}if(e.key==='Enter'&&count){open($$('[data-result]')[selected].dataset.result);$('#searchModal').classList.remove('open')}};render();setTimeout(()=>input.focus(),50)}
  $('#searchButton').onclick=()=>showSearch();$('#openSearchHero').onclick=()=>showSearch();$('#heroSearch').oninput=e=>{if(e.target.value.length>1)showSearch(e.target.value)};$('#showFavorites').onclick=()=>renderTools(tools.filter(t=>favs().includes(t.id)));
  $('#settingsButton').onclick=()=>$('#settingsModal').classList.add('open');$('#themeToggle').checked=localStorage.getItem('astra-light')==='1';$('#motionToggle').checked=localStorage.getItem('astra-motion')==='1';const apply=()=>{document.body.classList.toggle('light',$('#themeToggle').checked);document.body.classList.toggle('reduced-motion',$('#motionToggle').checked);localStorage.setItem('astra-light',$('#themeToggle').checked?'1':'0');localStorage.setItem('astra-motion',$('#motionToggle').checked?'1':'0')};$('#themeToggle').onchange=apply;$('#motionToggle').onchange=apply;apply();$('#clearData').onclick=()=>{if(confirm('Clear all AstraUtilities saved settings, favorites, and recents?')){Object.keys(localStorage).filter(k=>k.startsWith('astra-')).forEach(k=>localStorage.removeItem(k));location.reload()}};
  $('#menuButton').onclick=()=>showSearch();document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();showSearch()}if(e.key==='Escape')closeAll()});
  if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
